window.img = [
  // ABC
  /* this is the charset ... we cann drop/add any characters we might need ... that's why I went with that alphabet.indexOf thing */
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAATgAAAAIAgMAAAAQHAvgAAAACVBMVEVHcEx+JVP/owDMaL7dAAAAAXRSTlMAQObYZgAAASdJREFUKM9dUruxxCAMxIHdAQ5cDSUQIAIX8GZENQ58weUQqMunlcy7mwcjI+uzs4INRFRioawnxVIimUMJ4TVTNqO5tFQr1ryiI1OBb/85BFhoYrv7yWwnt9SY+eitm1lmriaHRVtn7Tou/w9huwyOHeD1Dw5f+ewJ9ZgCVeGhXbflZEnbFUtAislaX3rKfke0p/bFyFtgx9CKrtW9SlP/1CqSczTeru1Sjg8nYwee+80Ynfj9x0R2qcb9542xDgU/xzmqs5alo2ZJSzI4G9DYNR/Hx2P2Ox0YbLMbQhzecyVSB+oQqQJ2Pux8ilnYDdyegvNhN6WDGBzzB1ij4IqceoDTp9CHn0LJLpSYKbooVARhhWxUCKvKAXkXhqlG5QKJ+MawIfwCPVP2vlxyVvAAAAAASUVORK5CYII=',

  // Player
  'data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABQAAAAUCAYAAACNiR0NAAAA3ElEQVQ4y2NgGHGAkZCC90eq/gv8Y4cotqtnfH+k6j8DAwODoE0bI8kGwjQL/GNnOPlVmcGc+y7DB6afOA1jYGBgYCHGGye/KjOUNk9gOHzsDCNFXv5/qPH/ya/KKGIWnjF49TDhtc2untGc+y6y0FWqxNyJ7Uv+Uzs1EG0gEyEFymah/+MCLWCGclJkoLJZKLLLnjIwMDBT7EIY4Obll2ZgYPhClQCMC7T4n9C55wtVwpCBgYHhp7UWAwMDwwOqGUgKoLqBROXlZ+suMTAwXNKmugttrUyonmMIAgAWkDjgnFQiWgAAAABJRU5ErkJggg=='
];
